//VARIABLES
@RRHHtablesFuncionProcedures = http://localhost:4029/HUMAN_R.tablesFuncionProcedures
@RRHHDataFill = http://localhost:4029/HUMAN_R.INITIAL_DATA
@RRHHPerson = http://localhost:4029/HUMAN_R.PERSON
@RRHHContract = http://localhost:4029/HUMAN_R.CONTRACTS
@RRHHEmployee = http://localhost:4029/HUMAN_R.EMPLOYEES
@RRHHCompany = http://localhost:4029/HUMAN_R.COMPANY
@RRHHCountry = http://localhost:4029/HUMAN_R.COUNTRY
@RRHHDepartament = http://localhost:4029/HUMAN_R.DEPARTAMENT
@RRHHCities = http://localhost:4029/HUMAN_R.CITIES
@RRHHPosition = http://localhost:4029/HUMAN_R.POSITION
@RRHHSuburn = http://localhost:4029/HUMAN_R.SUBURN
@RRHHArea = http://localhost:4029/HUMAN_R.AREA
@RRHHAddress = http://localhost:4029/HUMAN_R.ADDRESS_LIST
@RRHHTelephone = http://localhost:4029/HUMAN_R.TELEPHONES
@RRHHTelephoneP = http://localhost:4029/HUMAN_R.TELEPHONES_PERSON
@RRHHClient= http://localhost:4029/HUMAN_R.CLIENT


GET {{RRHHPerson}}
###
GET {{RRHHContract}}
###
GET {{RRHHEmployee}}
###
GET {{RRHHCompany}}
###
GET {{RRHHCountry}}
###
GET {{RRHHDepartament}}
###
GET {{RRHHCities}}
###
GET {{RRHHPosition}}
###
GET {{RRHHSuburn}}
###
GET {{RRHHArea}}
###
GET {{RRHHAddress}}
###
GET {{RRHHTelephone}}
###
GET {{RRHHTelephoneP}}
###
GET {{RRHHClient}}


###
POST {{RRHHtablesFuncionProcedures}}
###
POST {{RRHHDataFill}}
###
POST {{RRHHPosition}}
###
POST {{RRHHCountry}}
###
POST {{RRHHDepartament}}
###
POST {{RRHHCities}}
###
POST {{RRHHSuburn}}
###
POST {{RRHHAddress}}
###
POST {{RRHHArea}}
###
POST {{RRHHPerson}}
###
POST {{RRHHContract}}
###
post {{RRHHEmployee}}
###
POST {{RRHHTelephone}}
###
POST {{RRHHTelephoneP}}
###
POST {{RRHHClient}}
###
//POST {{RRHHCompany}}






//Content-Type: application/json

# {
#     "var_firstName": "Jorge",
#     "var_secondName": "Aguileras",
#     "var_firstSurname": "Bustillo",
#     "var_secondSurname": "Alvarado",
#     "var_DNI": "0801200102454",
#     "dat_dateOfBirth": "1996/12/12",
#     "big_address_id_FK": 40,
#     "var_RTN_Personal": "76876540987876",
#     "cha_garder": "M"
# }