//VARIABLES
@RRHHtablesFuncionProcedures = http://localhost:4028/HUMAN_R.tablesFuncionProcedures
@RRHHDataFill = http://localhost:4028/HUMAN_R.INITIAL_DATA
@RRHHPerson = http://localhost:4028/HUMAN_R.PERSON
@RRHHContract = http://localhost:4028/HUMAN_R.CONTRACTS
@RRHHEmployee = http://localhost:4028/HUMAN_R.EMPLOYEES
@RRHHCompany = http://localhost:4028/HUMAN_R.COMPANY
@RRHHCountry = http://localhost:4028/HUMAN_R.COUNTRY
@RRHHDepartament = http://localhost:4028/HUMAN_R.DEPARTAMENT
@RRHHCities = http://localhost:4028/HUMAN_R.CITIES


GET {{RRHHPerson}}
###
GET {{RRHHContract}}
###
GET {{RRHHEmployee}}
###
GET {{RRHHCompany}}
###
GET {{RRHHCountry}}
###
GET {{RRHHDepartament}}
###
GET {{RRHHCities}}


###
POST {{RRHHtablesFuncionProcedures}}
###
POST {{RRHHDataFill}}
###
POST {{RRHHCompany}}
###
POST {{RRHHCountry}}
###
POST {{RRHHDepartament}}
###
POST {{RRHHCities}}
###
POST {{RRHHPerson}}
###
POST {{RRHHContract}}
###
post {{RRHHEmployee}}








//Content-Type: application/json

# {
#     "var_firstName": "Jorge",
#     "var_secondName": "Aguileras",
#     "var_firstSurname": "Bustillo",
#     "var_secondSurname": "Alvarado",
#     "var_DNI": "0801200102454",
#     "dat_dateOfBirth": "1996/12/12",
#     "big_address_id_FK": 40,
#     "var_RTN_Personal": "76876540987876",
#     "cha_garder": "M"
# }