version: "3.7"

services:
  app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - fill

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1544:1433"
    environment:
      SA_PASSWORD: "BD2_Grupo1"
      ACCEPT_EULA: "Y"
    networks:
      - fill

networks:
  fill:





  
  
